--1
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY 1 ASC;
--2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;
--3
SELECT STUDENT_NAME AS "학생이름", 
        STUDENT_NO AS "학번", 
        STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE NOT STUDENT_NO LIKE 'A%'
    AND (STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '강원도%')
ORDER BY 1 ASC;
--4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY 2 ASC;
--5
SELECT STUDENT_NO, TO_CHAR(POINT, '9.99') AS "POINT"
FROM TB_GRADE
WHERE TERM_NO = '200402' 
    AND CLASS_NO = 'C3118100'
ORDER BY 2 DESC, 1 ASC;
--6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2 ASC;
--7
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);
--8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR
JOIN TB_CLASS USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO);
--9
SELECT C.CLASS_NAME, P.PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR CP
JOIN TB_CLASS C ON (CP.CLASS_NO = C.CLASS_NO)
JOIN TB_PROFESSOR P ON (CP.PROFESSOR_NO = P.PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.CATEGORY = '인문사회';
--10
SELECT G.STUDENT_NO AS "학번",
        S.STUDENT_NAME AS "학생 이름",
        ROUND(AVG(G.POINT), 1) AS "전체 평점"
FROM TB_GRADE G
JOIN TB_STUDENT S ON (G.STUDENT_NO = S.STUDENT_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NAME = '음악학과'
GROUP BY G.STUDENT_NO, S.STUDENT_NAME;
--11
SELECT D.DEPARTMENT_NAME AS "학과이름",
        S.STUDENT_NAME AS "학생이름",
        P.PROFESSOR_NAME AS "지도교수이름"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE S.STUDENT_NO = 'A313047';
--12
SELECT S.STUDENT_NAME, G.TERM_NO AS "TERM_NAME"
FROM TB_GRADE G
JOIN TB_STUDENT S ON (G.STUDENT_NO = S.STUDENT_NO)
JOIN TB_CLASS C ON (G.CLASS_NO = C.CLASS_NO)
WHERE G.TERM_NO LIKE '2007%' AND C.CLASS_NAME = '인간관계론';
--13
SELECT C.CLASS_NAME, D.DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR CP ON (C.CLASS_NO = CP.CLASS_NO)
WHERE D.CATEGORY = '예체능' AND CP.PROFESSOR_NO IS NULL;
--14
SELECT S.STUDENT_NAME AS "학생이름", NVL(P.PROFESSOR_NAME, '지도교수 미지정') AS "지도교수"
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NAME = '서반아어학과'
ORDER BY ENTRANCE_DATE ASC;
--15
SELECT S.STUDENT_NO AS "학번",
        S.STUDENT_NAME AS "이름",
        D.DEPARTMENT_NAME AS "학과 이름",
        G."평점"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN (SELECT STUDENT_NO, AVG(POINT) AS "평점"
        FROM TB_GRADE
        GROUP BY STUDENT_NO) G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE S.ABSENCE_YN = 'N' AND G."평점" >= 4.0
ORDER BY 1 ASC;
--16
SELECT C.CLASS_NO, C.CLASS_NAME, AVG(G.POINT)
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_GRADE G ON (C.CLASS_NO = G.CLASS_NO)
WHERE D.DEPARTMENT_NAME = '환경조경학과' AND C.CLASS_TYPE LIKE '전공%'
GROUP BY C.CLASS_NO, C.CLASS_NAME
ORDER BY 1 ASC;
--17
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                        FROM TB_STUDENT
                        WHERE STUDENT_NAME = '최경희');
--18
WITH EXAMPLE AS (
    SELECT G.STUDENT_NO, AVG(G.POINT) AS "평점"
    FROM TB_GRADE G
    JOIN TB_STUDENT S ON(G.STUDENT_NO = S.STUDENT_NO)
    JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
    WHERE DEPARTMENT_NAME = '국어국문학과'
    GROUP BY G.STUDENT_NO
)

SELECT S.STUDENT_NO, S.STUDENT_NAME
FROM TB_STUDENT S
JOIN EXAMPLE E ON (S.STUDENT_NO = E.STUDENT_NO)
WHERE E."평점" = (SELECT MAX("평점") FROM EXAMPLE);
--19
SELECT DEPARTMENT_NAME AS "계열 학과명", ROUND(AVG(POINT), 1) AS "전공평점"
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE CATEGORY = (SELECT CATEGORY
                  FROM TB_DEPARTMENT
                  WHERE DEPARTMENT_NAME = '환경조경학과')
    AND TB_CLASS.CLASS_TYPE LIKE '전공%'
GROUP BY DEPARTMENT_NAME
ORDER BY 1 ASC;